import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({ blogs }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

       
          <div className={styles.grid}>
            {blogs.map((blog) => (
                <a href="https://nextjs.org/docs" className={styles.card} key={blog.id}>
                  <h2>{blog.title} &rarr;</h2>
                  <p>{blog.content}</p>
                </a>
            ))}
          </div>     

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`https://morning-scrubland-44390.herokuapp.com/blogs`)
  const blogs = await res.json()
  return {
      props: {  // will be passed to the page component as props
          blogs
      }
  }
}